### ISSUE TITLE
just getting server address

### ISSUE THREAD

**Issue by cydia1337** [JadlionHD/GrowServer#10]
![resim_2024-02-07_224044805](https://github.com/JadlionHD/GrowServer/assets/65765968/349dd53b-a2b0-4849-9ba9-e282281069e0)

**Comment by nob345** [comment]
I had the same error. If you connect to port 443, it will be fixed. Or with the https port specified in the webserver.ts file

**Comment by cydia1337** [comment]
> I had the same error. If you connect to port 443, it will be fixed. Or with the https port specified in the webserver.ts file

    httpServer.listen(80);
    httpsServer.listen(443);

**Comment by nob345** [comment]
Change 443 to 8080 then connect to 8080 port

**Comment by JadlionHD** [comment]
Solved on discord. Closing
