### ISSUE TITLE
Fixed paint colors in Tiles

### ISSUE THREAD

**Issue by smailiukas** [JadlionHD/GrowServer#11]
FLAGS_BLUE: 0x8000,
FLAGS_GREEN: 0x4000,
FLAGS_YELLOW: 0x6000,
FLAGS_PURPLE: 0xA000

For some reason blue was green and green was blue so i reversed it and added 2 more colors yellow and purple

**Comment by JadlionHD** [comment]
https://github.com/JadlionHD/GrowServer/commit/319a847863a1ffa3ee7a944e5a9ee00eadaba8a6
