### ISSUE TITLE
How can I lock items like Dgate, Portcullis?

### ISSUE THREAD

**Issue by nob345** [JadlionHD/GrowServer#12]
**Problems**
- In order for blocks like dgate, portcullis to work on my server, I changed the place.ts and player.ts file and created dialogs for these blocks. I shared the changed parts below. Anyway, how do I lock or unlock these blocks and let other players interact with them?

**Place.ts**
- `case ActionTypes.SWITCHEROO: { //dgate
        p.block.switch = { locked: true};

        this.world.place({
          peer: this.peer,
          x: p.block.x,
          y: p.block.y,
          isBg: p.isBg,
          id: p.id
        });

        this.tileUpdate(p.actionType, p.block);
        return true;
      }`
- `case ActionTypes.GATEWAY: {
        p.block.gateway = { locked: true};

        this.world.place({
          peer: this.peer,
          x: p.block.x,
          y: p.block.y,
          isBg: p.isBg,
          id: p.id
        });

        this.tileUpdate(p.actionType, p.block);
        return true;
      }`

**Player.ts**
- `case ActionTypes.SWITCHEROO: {
        if (this.world.data.owner) {
          if (this.world.data.owner.id !== this.peer.data?.id_user) return;
        }
        const dialog = new DialogBuilder()
          .defaultColor()
          .addQuickExit()
          .addLabelWithIcon(`\`wEdit ${itemMeta.name}\`\``, itemMeta.id as number, "big")
          .addCheckbox("lock", "Is open to public", "NOT_SELECTED")
          .embed("tilex", block.x)
          .embed("tiley", block.y)
          .embed("itemID", itemMeta.id)
          .endDialog("switch_end", "Cancel", "OK")
          .str();
        this.peer.send(Variant.from("OnDialogRequest", dialog));
        break;
      }
      case ActionTypes.GATEWAY: {
        if (this.world.data.owner) {
          if (this.world.data.owner.id !== this.peer.data?.id_user) return;
        }

        const dialog = new DialogBuilder()
          .defaultColor()
          .addQuickExit()
          .addLabelWithIcon(`\`wEdit ${itemMeta.name}\`\``, itemMeta.id as number, "big")
          .addCheckbox("lock", "Is open to public", "not_selected")
          .embed("tilex", block.x)
          .embed("tiley", block.y)
          .embed("itemID", itemMeta.id)
          .endDialog("gateway_end", "Cancel", "OK")
          .str();
        this.peer.send(Variant.from("OnDialogRequest", dialog));
        break;
      }`

**GatewayEnd.ts**
- const world = peer.hasWorld(peer.data.world);
    const pos = parseInt(action.tilex) + parseInt(action.tiley) * (world?.data.width as number);
    const block = world?.data.blocks[pos] as Block;
    const itemMeta = this.base.items.metadata.items.find((i) => i.id === parseInt(action.itemID));

    if (world?.data.owner) {
      if (world?.data.owner.id !== peer.data?.id_user) return;
    }

    const lockname = action.lock === "1" ? true : false;

    block.gateway.locked = lockname;

    Place.tileUpdate(this.base, peer, itemMeta?.type || 0, block, world as World);

**Information**
- Growtopia Version: 4.50
- Nodejs Version: v.21.6.1

**Comment by JadlionHD** [comment]
## SWITCHEROO
you need to handle [onDamage](https://github.com/JadlionHD/GrowServer/blob/main/src/tanks/Punch.ts#L82) method so when if a player punches dgate it will change the value of the toggleable. example:
```js
// boolean
block.toggleable.open = !block.toggleable.open;
// update tile
```

## Tile Flags
to be able player & other player see if the dgate are open/closed, you need to set the flags of the block to these flags [Flags](https://github.com/JadlionHD/GrowServer/blob/65e4d8ab077e0a4e1fa18b23ac1096f0972ee46d/src/utils/enums/Tiles.ts#L1)
```js
case ActionTypes.SWITCHEROO: {
  let flag = 0x0;
  buf = Buffer.alloc(8);
  
  if (block.toggleable?.open) flag |= Flags.FLAGS_OPEN; // if the block was closed then dont give FLAGS_LOCKED since its for door only.
  if (block.toggleable?.openToPublic) flags |= Flags.FLAGS_PUBLIC;
  
  buf.writeUInt32LE(block.fg | (block.bg << 16));
  buf.writeUint16LE(lockPos, 4);
  buf.writeUint16LE(flag, 6);
  break;
}
```

also for `FLAGS_PUBLIC` I'll assuming that player no access might be able to punch it, maybe TIAS.

**Comment by nob345** [comment]
I don't fully understand how to do this and I feel like an idiot. Can you please help me if you are not busy? I added your code under the SEED action in the onPunch event and it didn't work. Normally I am more resourceful .d
