### ISSUE TITLE
No explanation of how to enter or join the server

### ISSUE THREAD

**Issue by GTPManager** [JadlionHD/GrowServer#5]
I make a txt file right, with the ip adress and everything, 
0.0.0.0 growtopia1.com
0.0.0.0 growtopia2.com
I tried other gtps txt file examples, help please, people cant join, i cant join. I am hosting it on a node js server.

**Comment by dearminder** [comment]
Maby try putting correct ip of machine your hosting it in

**Comment by JadlionHD** [comment]
I'll assuming this was solved at the discord server, closing.
feel free to re open / new issue if there's a issue
