### ISSUE TITLE
The Application was Forced to Exit

### ISSUE THREAD

**Issue by jonathanmarp** [JadlionHD/GrowServer#6]
Dear GrowServer Developers,

## Problems
I have problems doing `connect`. And I have the details and What happened.

## Details
- Growtopia: `Version 4.05`
- Nodejs: `Version 20.3.1`

## What Happen
I have done everything that was instructed. And I set the host on the right IP. 
When I do `connect` and in the Updating Item log, I exit the application by itself.

```json
{
  parsed: {
    tankIDName: 'admin',
    tankIDPass: 'admin',
    requestedName: 'BraveTiny',
    f: '1',
    protocol: '175',
    game_version: '4.01',
    fz: '16474664',
    lmode: '0',
    cbits: '1024',
    player_age: '24',
    GDPR: '1',
    category: '_12',
    totalPlaytime: '0',
    hash2: '1318604448',
    meta: 'lolwhat',
    fhash: '-716928004',
    rid: '01DB992F19676EC6019AF77222F6FF98',
    platformID: '0,1,1',
    deviceVersion: '0',
    country: 'us',
    hash: '403377526',
    mac: 'e4:fd:45:ab:a5:63',
    wk: '3E596CE6CB01F2CB5524C417D24337C4',
    zf: '-1434588773'
  },
  dataType: 2
}
{ parsed: { action: 'refresh_item_data' }, dataType: 2 }
Unknown tank TankPacket {
  data: {
    packetType: 4,
    type: 24,
    punchID: 0,
    buildRange: 0,
    punchRange: 0,
    netID: -1,
    targetNetID: 0,
    state: 0,
    info: 1125432991,
    xPos: 0,
    yPos: 0,
    xSpeed: 0,
    ySpeed: 0,
    xPunch: 0,
    yPunch: 0
  }
}
```

## What do I have to do
- Is there a specific version of Growtopia ?
- Does the server have to be placed on a Virtual Host ?

**Comment by JadlionHD** [comment]
It seems that you're using an older version of Growtopia.
The problem come from items.dat, since the source are using v4.31 (Latest v4.36) Growtopia items.dat.
Maybe try changing the items.dat with your growtopia version or update the growtopia to newer version

**Comment by jonathanmarp** [comment]
Yeah, It works.
Thank's @JadlionHD
