### ISSUE TITLE
Cannot Enter World

### ISSUE THREAD

**Issue by jonathanmarp** [JadlionHD/GrowServer#8]
Dear **GrowServer Developer**,

## Problems
When I logged in for the first time. 
And when I want to create a world for the first time, the application experiences lag. 
And don't enter the world. And loading `Entering World..` continuously, 
After that go back to log in. And it happens continuously.

## Specific
- Growtopia `Version 4.29`
  - `Version 4.36`, Windows **can't be opened**
- Nodejs `Version 20.3.1`

**Comment by jonathanmarp** [comment]
## What I Found
I just found out about the **problem**,

Namely the write and read speed to the database is very long.
I have changed From **sqlite3** to **mysql**. And it worked.

## Other Issue
- After I entered the world. I **reconnected** and I don't know why it happened.
- By the way, every time I create a new world, everything will be made into water.

**Comment by JadlionHD** [comment]
> ## Other Issue
> - After I entered the world. I reconnected and I don't know why it happened.
> - By the way, every time I create a new world, everything will be made into water.

Growtopia made a change with their world visual generation, since you're using an older gt version maybe that's the case.

**Comment by jonathanmarp** [comment]
Maybe I will do it after the new version supports Windows operating systems.
